[context.production.environment]
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "false"
  HUGO_VERSION = "0.89.4"
  
 [build.environment]
  HUGO_VERSION = "0.89.4"
  NODE_VERSION = "16.17.1"
  NPM_VERSION = "8.15.0"